#!/bin/bash

set -uo pipefail
IFS=$'\n\t'

TEST_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPOSITORY_ROOT=$(cd "$TEST_DIR/../.." && pwd)
REFERENCE_SCRIPT="$REPOSITORY_ROOT/tools/reference/slack-update-reference.sh"

# Source the reference implementation without invoking main().
# shellcheck source=../../tools/reference/slack-update-reference.sh
source "$REFERENCE_SCRIPT"

TEST_COUNT=0
FAILURE_COUNT=0

pass() {
    TEST_COUNT=$((TEST_COUNT + 1))
}

fail() {
    local message=$1

    TEST_COUNT=$((TEST_COUNT + 1))
    FAILURE_COUNT=$((FAILURE_COUNT + 1))
    printf 'FAIL: %s\n' "$message" >&2
}

assert_equal() {
    local expected=$1
    local actual=$2
    local message=$3

    if [ "$actual" = "$expected" ]; then
        pass
    else
        fail "$message (expected '$expected', got '$actual')"
    fi
}

assert_file_equal() {
    local expected=$1
    local actual=$2
    local message=$3

    if cmp -s "$expected" "$actual"; then
        pass
    else
        fail "$message"
        diff -u "$expected" "$actual" >&2 || true
    fi
}

assert_file_empty() {
    local path=$1
    local message=$2

    if [ -f "$path" ] && [ ! -s "$path" ]; then
        pass
    else
        fail "$message"
    fi
}

assert_target_selected() {
    local line=$1
    local expected=$2

    if sbo_target_from_queue_line "$line"; then
        assert_equal "$expected" "$SBO_QUEUE_LINE_TARGET" \
            "queue target mismatch for line: $line"
    else
        fail "valid queue target was rejected: $line"
    fi
}

assert_target_skipped() {
    local line=$1
    local status

    if sbo_target_from_queue_line "$line"; then
        fail "queue control or empty line was selected as a target: $line"
    else
        status=$?
        assert_equal 1 "$status" "queue control line should be skipped: $line"
    fi
}

assert_target_rejected() {
    local line=$1
    local status

    if sbo_target_from_queue_line "$line"; then
        fail "unsafe queue target was accepted: $line"
    else
        status=$?
        assert_equal 2 "$status" "unsafe queue target should be rejected: $line"
    fi
}

assert_target_selected 'alpha' 'alpha'
assert_target_selected '  gtk+3  ' 'gtk+3'
assert_target_selected $'OpenCASCADE\t| FFMPEG=yes FREEIMAGE=yes' 'OpenCASCADE'
assert_target_selected 'python3-PyYAML|TESTS=no' 'python3-PyYAML'
assert_target_selected 'libbar # local comment' 'libbar'
assert_target_selected $'libfoo\r' 'libfoo'
assert_target_skipped ''
assert_target_skipped '   '
assert_target_skipped '# generated queue'
assert_target_skipped '  # generated queue'
assert_target_skipped '@shared-dependencies'
assert_target_skipped '@shared-dependencies # recursive queue'
assert_target_skipped '-optional-package'
assert_target_rejected '../escape'
assert_target_rejected '/absolute/path'
assert_target_rejected 'bad$name'
assert_target_rejected 'two package names'

normalized=$(printf '%s\n' zeta alpha 'gtk+3' alpha | normalize_sbo_target_names_from_stream)
assert_equal $'alpha\ngtk+3\nzeta' "$normalized" \
    'target normalization must use a deterministic C-locale unique order'

if printf '%s\n' alpha '../escape' | normalize_sbo_target_names_from_stream >/dev/null; then
    fail 'target normalization should reject unsafe names'
else
    pass
fi

TEST_TMP=$(mktemp -d)
trap 'rm -rf "$TEST_TMP"' EXIT

QUEUE_DIR_A="$TEST_TMP/queues-a"
QUEUE_DIR_B="$TEST_TMP/queues-b"
mkdir -p "$QUEUE_DIR_A/nested" "$QUEUE_DIR_B/nested"

cat > "$QUEUE_DIR_A/z-last.sqf" <<'EOF_QUEUE_A1'
zeta
alpha
OpenCASCADE | FFMPEG=yes FREEIMAGE=yes
@shared
-disabled
EOF_QUEUE_A1
cat > "$QUEUE_DIR_A/nested/a-first.sqf" <<'EOF_QUEUE_A2'
# generated by sqg
gtk+3
alpha
libfoo | FEATURE=yes
EOF_QUEUE_A2
printf '%s\n' ignored > "$QUEUE_DIR_A/not-a-queue.txt"

cat > "$QUEUE_DIR_B/a-first.sqf" <<'EOF_QUEUE_B1'
libfoo | FEATURE=yes
alpha
gtk+3
EOF_QUEUE_B1
cat > "$QUEUE_DIR_B/nested/z-last.sqf" <<'EOF_QUEUE_B2'
-disabled
@shared
OpenCASCADE | FFMPEG=yes FREEIMAGE=yes
alpha
zeta
EOF_QUEUE_B2

EXPECTED_QUEUE_TARGETS="$TEST_TMP/expected-queue-targets"
cat > "$EXPECTED_QUEUE_TARGETS" <<'EOF_EXPECTED_QUEUE'
OpenCASCADE
alpha
gtk+3
libfoo
zeta
EOF_EXPECTED_QUEUE

SELECTED_A="$TEST_TMP/selected-a"
SELECTED_B="$TEST_TMP/selected-b"
if collect_sbo_targets_from_queue_directory "$QUEUE_DIR_A" "$SELECTED_A"; then
    pass
else
    fail "first queue directory selection failed: $SBO_TARGET_SELECTION_ERROR"
fi
if collect_sbo_targets_from_queue_directory "$QUEUE_DIR_B" "$SELECTED_B"; then
    pass
else
    fail "second queue directory selection failed: $SBO_TARGET_SELECTION_ERROR"
fi
assert_file_equal "$EXPECTED_QUEUE_TARGETS" "$SELECTED_A" \
    'queue selection should contain only canonical package targets'
assert_file_equal "$SELECTED_A" "$SELECTED_B" \
    'queue target selection must not depend on file names, layout, or line order'

MISSING_TARGETS="$TEST_TMP/missing-targets"
if collect_sbo_targets_from_queue_directory "$TEST_TMP/no-such-directory" "$MISSING_TARGETS"; then
    pass
else
    fail 'a missing optional queue directory should produce an empty target set'
fi
assert_file_empty "$MISSING_TARGETS" \
    'a missing optional queue directory should install an empty target set'

INVALID_QUEUE_DIR="$TEST_TMP/invalid-queues"
mkdir -p "$INVALID_QUEUE_DIR"
printf '%s\n' '../escape' > "$INVALID_QUEUE_DIR/invalid.sqf"
ATOMIC_TARGETS="$TEST_TMP/atomic-targets"
printf '%s\n' preserved > "$ATOMIC_TARGETS"
if collect_sbo_targets_from_queue_directory "$INVALID_QUEUE_DIR" "$ATOMIC_TARGETS"; then
    fail 'invalid queue targets should make selection fail'
else
    pass
fi
assert_equal 'preserved' "$(cat "$ATOMIC_TARGETS")" \
    'failed queue selection must not replace the previous target set'
assert_equal "queue contains an invalid SBo target: $INVALID_QUEUE_DIR/invalid.sqf" \
    "$SBO_TARGET_SELECTION_ERROR" \
    'invalid queue selection should expose a stable diagnostic'

PACKAGE_DATABASE="$TEST_TMP/packages"
SBO_PACKAGE_TAG=_SBo
mkdir -p "$PACKAGE_DATABASE"
: > "$PACKAGE_DATABASE/zeta-1.0-x86_64-1_SBo"
: > "$PACKAGE_DATABASE/alpha-1.0-x86_64-1_SBo"
: > "$PACKAGE_DATABASE/alpha-2.0-x86_64-2_SBo"
: > "$PACKAGE_DATABASE/gtk+3-3.24.49-x86_64-1_SBo"
: > "$PACKAGE_DATABASE/not-sbo-1.0-x86_64-1"
: > "$PACKAGE_DATABASE/name_SBo-1.0-x86_64-1"
: > "$PACKAGE_DATABASE/wrong-suffix-1.0-x86_64-1_SBo_debug"

INSTALLED_TARGETS="$TEST_TMP/installed-targets"
EXPECTED_INSTALLED="$TEST_TMP/expected-installed"
cat > "$EXPECTED_INSTALLED" <<'EOF_EXPECTED_INSTALLED'
alpha
gtk+3
zeta
EOF_EXPECTED_INSTALLED

if collect_installed_sbo_targets "$INSTALLED_TARGETS"; then
    pass
else
    fail "installed SBo target selection failed: $SBO_TARGET_SELECTION_ERROR"
fi
assert_file_equal "$EXPECTED_INSTALLED" "$INSTALLED_TARGETS" \
    'installed SBo selection must use the exact build suffix and deduplicate package names'

CORE_TARGETS="$TEST_TMP/core-targets"
EXTRA_TARGETS="$TEST_TMP/extra-targets"
FINAL_TARGETS="$TEST_TMP/final-targets"
printf '%s\n' zeta alpha duplicate > "$CORE_TARGETS"
printf '%s\n' duplicate beta alpha > "$EXTRA_TARGETS"
if merge_sbo_target_sets "$FINAL_TARGETS" "$CORE_TARGETS" "$EXTRA_TARGETS"; then
    pass
else
    fail 'final SBo target-set merge failed'
fi
assert_equal $'alpha\nbeta\nduplicate\nzeta' "$(cat "$FINAL_TARGETS")" \
    'final SBo target selection must be a deterministic sorted union'

BROKEN="$TEST_TMP/broken"
QUEUE_EXTRA="$TEST_TMP/broken-extra"
BROKEN_BIN_A="$TEST_TMP/bin-a"
BROKEN_BIN_Z="$TEST_TMP/bin-z"
: > "$BROKEN_BIN_A"
: > "$BROKEN_BIN_Z"
printf '%s\n' existing-target > "$QUEUE_EXTRA"
printf '%s\n%s\n' "$BROKEN_BIN_Z" "$BROKEN_BIN_A" > "$BROKEN"
printf '%s\n' "${BROKEN_BIN_Z#/}" > "$PACKAGE_DATABASE/owner-z-1.0-x86_64-1_SBo"
printf '%s\n' "$BROKEN_BIN_A" > "$PACKAGE_DATABASE/owner-a-1.0-x86_64-1_SBo"
printf '%s\n' "$BROKEN_BIN_A" > "$PACKAGE_DATABASE/owner-native-1.0-x86_64-1"

if map_broken_objects_to_sbo_packages >/dev/null; then
    pass
else
    fail "broken-object SBo target mapping failed: $SBO_TARGET_SELECTION_ERROR"
fi
assert_equal $'existing-target\nowner-a\nowner-z' "$(cat "$QUEUE_EXTRA")" \
    'broken-object owners must be selected by exact SBo suffix and merged deterministically'
assert_equal 3 "$TOTAL_EXTRA" \
    'broken-object mapping should report the selected extra-target count'

QUEUE_CORE="$TEST_TMP/apply-core"
QUEUE_EXTRA="$TEST_TMP/apply-extra"
QUEUE_FINAL="$TEST_TMP/apply-final"
BROKEN="$TEST_TMP/apply-broken"
STILL_BROKEN="$TEST_TMP/still-broken"
LOG="$TEST_TMP/test.log"
: > "$BROKEN"
SBO_CALL="$TEST_TMP/sbopkg-call"

sbopkg() {
    printf '%s\n' "$*" > "$SBO_CALL"
    return 0
}

printf '%s\n' '../escape' > "$QUEUE_CORE"
: > "$QUEUE_EXTRA"
printf '%s\n' preserved > "$QUEUE_FINAL"
rm -f "$SBO_CALL"
if build_and_apply_sbo_queue >/dev/null; then
    fail 'an unsafe final SBo target should block queue submission'
else
    pass
fi
assert_equal preserved "$(cat "$QUEUE_FINAL")" \
    'failed final target selection must preserve the previous submitted set'
if [ -e "$SBO_CALL" ]; then
    fail 'sbopkg must not run after final target selection fails'
else
    pass
fi
assert_equal 1 "$SBO_BUILD_STATUS" \
    'failed final target selection should record a non-zero SBo build status'

printf '%s\n' zeta alpha > "$QUEUE_CORE"
printf '%s\n' beta alpha > "$QUEUE_EXTRA"
rm -f "$SBO_CALL"
if build_and_apply_sbo_queue >/dev/null; then
    pass
else
    fail 'deterministic final SBo target set should be submitted successfully'
fi
assert_equal $'alpha\nbeta\nzeta' "$(cat "$QUEUE_FINAL")" \
    'submitted SBo target file must use the deterministic selected set'
assert_equal 3 "$TOTAL_EN_COLA" \
    'submitted SBo target count should match the deterministic set'
assert_equal "-b
-B
$QUEUE_FINAL" "$(cat "$SBO_CALL")" \
    'sbopkg should receive the selected target file through -B'
assert_equal 0 "$SBO_BUILD_STATUS" \
    'successful deterministic target submission should record status zero'

initialize_runtime_state
FLATPAK_MODE=disabled
SBO_MODE=auto
ELF_MODE=disabled
CINNAMON_MODE=disabled
BOOT_MODE=disabled
FLATPAK_MODULE_STATE=disabled
SBO_MODULE_STATE=available
SBO_MODULE_RUN=1
ELF_MODULE_STATE=disabled
CINNAMON_MODULE_STATE=disabled
BOOT_MODULE_STATE=disabled
PACKAGE_SNAPSHOT_BEFORE_VALID=1
PACKAGE_SNAPSHOT_AFTER_VALID=1
SLACKPKG_UPDATE_STATUS=0
SLACKPKG_INSTALL_NEW_STATUS=0
SLACKPKG_UPGRADE_ALL_STATUS=0
SBOPKG_SYNC_STATUS=0
SQG_SYNC_STATUS=0
SBO_TARGET_SELECTION_STATUS=1
SBO_TARGET_SELECTION_ERROR='queue contains an invalid SBo target'
: > "$BROKEN"
JSON_FRAGMENT="$TEST_TMP/apply-json-fragment"
print_apply_json_modules > "$JSON_FRAGMENT"
if grep -Fq '"state": "failed"' "$JSON_FRAGMENT"; then
    pass
else
    fail 'provisional JSON should mark the SBo module failed after target-selection failure'
fi
if grep -Fq '"target_selection_exit_code": 1' "$JSON_FRAGMENT"; then
    pass
else
    fail 'provisional JSON should expose the SBo target-selection status'
fi
if grep -Fq '"target_selection_error": "queue contains an invalid SBo target"' "$JSON_FRAGMENT"; then
    pass
else
    fail 'provisional JSON should expose the SBo target-selection diagnostic'
fi

printf 'SBo target selection tests: %d checks, %d failures\n' "$TEST_COUNT" "$FAILURE_COUNT"
[ "$FAILURE_COUNT" -eq 0 ]
